apiVersion: v1
kind: ReplicationController
metadata:
  name: demo56
  namespace: com-att-ocnp-mgmt
spec:
  replicas: 1
  selector:
    app: demo56
  template:
    metadata:
      labels:
        app: demo56
    spec:
      serviceAccount: YOUR
      containers:
      - name: demo56
        image: ${docker-registry}/${docker-namespace}/demo56:latest
        imagePullPolicy: Always
        ports:
         - containerPort: 8080